### PR TITLE
Added cargo config file.

### PR DESCRIPTION
**Pull request by davidknight-seequent**

### CODE REVIEW

**Comment by davidknight-seequent** [comment]
This config file works when running locally but not in GitHub actions. Does anyone know why that might be?

**Review by Tim-Evans-Seequent — APPROVED** [review]

**Review by zinovya — APPROVED** [review]

**Comment by davidknight-seequent** [comment]
@zinovya During my investigations I updated the versions of most/all dependencies in the Cargo.toml files. Turns out the versions weren't the cause of the problem, so I can either revert those changes or leave them as they are. What is your preference?

**Comment by zinovya** [comment]
I don't have a preference. Maybe @Tim-Evans-Seequent has.

**Comment by Tim-Evans-Seequent** [comment]
I'm fine with updating dependencies until OMF2 reaches a release version.

**Comment by Tim-Evans-Seequent** [comment]
Oh, wait, everything except `zip` is fine. There is a bug in ZIP64 support so we can't upgrade that.

**Pull request merged**
