### PR TITLE
Add initial documentation generation using Sphinx

### PR DESCRIPTION
**Pull request by andrew-catalyst**

### CODE REVIEW

**Comment by antbrown** [comment]
Might just need a `cargo fmt --all`

**Comment by andrew-catalyst** [comment]
> Might just need a `cargo fmt --all`

Ok. I'm confused why that's coming up here, I didn't change it?

**Comment by antbrown** [comment]
> > Might just need a `cargo fmt --all`
> 
> Ok. I'm confused why that's coming up here, I didn't change it?

it might have been a pre-existing issue that I fixed in my branch before I knew to do the rebasing? if this branch was created before my pointset branch got merged then that might explain it?

**Comment by andrew-catalyst** [comment]
> > > Might just need a `cargo fmt --all`
> > 
> > 
> > Ok. I'm confused why that's coming up here, I didn't change it?
> 
> it might have been a pre-existing issue that I fixed in my branch before I knew to do the rebasing? if this branch was created before my pointset branch got merged then that might explain it?

Ah I was still rebasing off the old repo. Should be fixed now.

**Review by antbrown — APPROVED** [review]

**Pull request merged**
